"""add estoque saldo movimentacao produto certificado nfe

Revision ID: 57a8bb43b573
Revises: d4e5f6g7h8i9
Create Date: 2026-04-24 21:46:56.850915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57a8bb43b573'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6g7h8i9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificado_digital',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cnpj_certificado', sa.String(length=14), nullable=False),
    sa.Column('razao_social_certificado', sa.String(length=255), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('senha_criptografada', sa.String(length=500), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('valido', 'expirado', 'invalido', name='statuscertificado', schema='concilia'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_certificado_digital_id'), 'certificado_digital', ['id'], unique=False, schema='concilia')
    op.create_table('estoque_alerta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('sem_depara', 'estoque_negativo', 'periodo_reaberto', name='tipoalerta', schema='concilia'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_estoque_alerta_id'), 'estoque_alerta', ['id'], unique=False, schema='concilia')
    op.create_table('nfe_entrada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('numero_nf', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=5), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_autorizacao', sa.Date(), nullable=True),
    sa.Column('cnpj_emitente', sa.String(length=14), nullable=False),
    sa.Column('razao_social_emitente', sa.String(length=255), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('autorizada', 'cancelada', 'denegada', name='statusnfe', schema='concilia'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'chave_acesso', name='uq_nfe_entrada_chave'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_nfe_entrada_id'), 'nfe_entrada', ['id'], unique=False, schema='concilia')
    op.create_table('nfe_saida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('numero_nf', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=5), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_autorizacao', sa.Date(), nullable=True),
    sa.Column('cnpj_destinatario', sa.String(length=14), nullable=True),
    sa.Column('razao_social_destinatario', sa.String(length=255), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('autorizada', 'cancelada', 'denegada', name='statusnfe', schema='concilia'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'chave_acesso', name='uq_nfe_saida_chave'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_nfe_saida_id'), 'nfe_saida', ['id'], unique=False, schema='concilia')
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cnpj_filial', sa.String(length=14), nullable=True),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('unidade_estoque', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_produto_id'), 'produto', ['id'], unique=False, schema='concilia')
    op.create_table('estoque_movimentacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', 'ajuste', 'estorno', name='tipomovimentacao', schema='concilia'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('documento_origem', sa.String(length=100), nullable=True),
    sa.Column('justificativa', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['concilia.produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_estoque_movimentacao_id'), 'estoque_movimentacao', ['id'], unique=False, schema='concilia')
    op.create_table('estoque_saldo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('entradas', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('saidas', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('ajustes', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('fechado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['concilia.produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'produto_id', 'periodo', name='uq_estoque_saldo_periodo'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_estoque_saldo_id'), 'estoque_saldo', ['id'], unique=False, schema='concilia')
    op.create_table('nfe_entrada_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nfe_entrada_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('codigo_produto_fornecedor', sa.String(length=100), nullable=True),
    sa.Column('descricao_produto', sa.String(length=255), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('unidade_comercial', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_total_item', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_convertida', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade_convertida', sa.String(length=20), nullable=True),
    sa.Column('vinculo_pendente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nfe_entrada_id'], ['concilia.nfe_entrada.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['concilia.produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_nfe_entrada_item_id'), 'nfe_entrada_item', ['id'], unique=False, schema='concilia')
    op.create_table('nfe_saida_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nfe_saida_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('codigo_produto_empresa', sa.String(length=100), nullable=True),
    sa.Column('descricao_produto', sa.String(length=255), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('unidade_comercial', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_total_item', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_convertida', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade_convertida', sa.String(length=20), nullable=True),
    sa.Column('vinculo_pendente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nfe_saida_id'], ['concilia.nfe_saida.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['concilia.produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_nfe_saida_item_id'), 'nfe_saida_item', ['id'], unique=False, schema='concilia')
    op.create_table('produto_fornecedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cnpj_fornecedor', sa.String(length=14), nullable=False),
    sa.Column('razao_social_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('codigo_produto_fornecedor', sa.String(length=100), nullable=False),
    sa.Column('descricao_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('unidade_compra', sa.String(length=20), nullable=False),
    sa.Column('fator_conversao', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('operacao_conversao', sa.Enum('multiplicar', 'dividir', name='operacaoconversao', schema='concilia'), nullable=False),
    sa.Column('unidade_convertida', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['concilia.produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_produto_fornecedor_id'), 'produto_fornecedor', ['id'], unique=False, schema='concilia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_concilia_produto_fornecedor_id'), table_name='produto_fornecedor', schema='concilia')
    op.drop_table('produto_fornecedor', schema='concilia')
    op.drop_index(op.f('ix_concilia_nfe_saida_item_id'), table_name='nfe_saida_item', schema='concilia')
    op.drop_table('nfe_saida_item', schema='concilia')
    op.drop_index(op.f('ix_concilia_nfe_entrada_item_id'), table_name='nfe_entrada_item', schema='concilia')
    op.drop_table('nfe_entrada_item', schema='concilia')
    op.drop_index(op.f('ix_concilia_estoque_saldo_id'), table_name='estoque_saldo', schema='concilia')
    op.drop_table('estoque_saldo', schema='concilia')
    op.drop_index(op.f('ix_concilia_estoque_movimentacao_id'), table_name='estoque_movimentacao', schema='concilia')
    op.drop_table('estoque_movimentacao', schema='concilia')
    op.drop_index(op.f('ix_concilia_produto_id'), table_name='produto', schema='concilia')
    op.drop_table('produto', schema='concilia')
    op.drop_index(op.f('ix_concilia_nfe_saida_id'), table_name='nfe_saida', schema='concilia')
    op.drop_table('nfe_saida', schema='concilia')
    op.drop_index(op.f('ix_concilia_nfe_entrada_id'), table_name='nfe_entrada', schema='concilia')
    op.drop_table('nfe_entrada', schema='concilia')
    op.drop_index(op.f('ix_concilia_estoque_alerta_id'), table_name='estoque_alerta', schema='concilia')
    op.drop_table('estoque_alerta', schema='concilia')
    op.drop_index(op.f('ix_concilia_certificado_digital_id'), table_name='certificado_digital', schema='concilia')
    op.drop_table('certificado_digital', schema='concilia')
