"""initial

Revision ID: 5bfb489bd4b2
Revises: 
Create Date: 2025-12-16 08:07:08.258585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfb489bd4b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_empresa_cnpj'), 'empresa', ['cnpj'], unique=True, schema='concilia')
    op.create_index(op.f('ix_concilia_empresa_id'), 'empresa', ['id'], unique=False, schema='concilia')
    op.create_table('plano_contas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conta_contabil', sa.String(length=50), nullable=False),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False),
    sa.Column('conciliavel', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('conta_superior', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_plano_contas_conta_contabil'), 'plano_contas', ['conta_contabil'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_plano_contas_conta_superior'), 'plano_contas', ['conta_superior'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_plano_contas_empresa_id'), 'plano_contas', ['empresa_id'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_plano_contas_id'), 'plano_contas', ['id'], unique=False, schema='concilia')
    op.create_index('ix_plano_contas_empresa_conta', 'plano_contas', ['empresa_id', 'conta_contabil'], unique=True, schema='concilia')
    op.create_table('conciliacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('conta_contabil_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('saldo', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_contabil_id'], ['concilia.plano_contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['concilia.empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_conciliacoes_conta_contabil_id'), 'conciliacoes', ['conta_contabil_id'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_conciliacoes_empresa_id'), 'conciliacoes', ['empresa_id'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_conciliacoes_id'), 'conciliacoes', ['id'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_conciliacoes_periodo'), 'conciliacoes', ['periodo'], unique=False, schema='concilia')
    op.create_table('arquivos_conciliacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conciliacao_id', sa.Integer(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=300), nullable=False),
    sa.Column('data_conciliacao', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conciliacao_id'], ['concilia.conciliacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='concilia'
    )
    op.create_index(op.f('ix_concilia_arquivos_conciliacao_conciliacao_id'), 'arquivos_conciliacao', ['conciliacao_id'], unique=False, schema='concilia')
    op.create_index(op.f('ix_concilia_arquivos_conciliacao_id'), 'arquivos_conciliacao', ['id'], unique=False, schema='concilia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concilia_arquivos_conciliacao_id'), table_name='arquivos_conciliacao', schema='concilia')
    op.drop_index(op.f('ix_concilia_arquivos_conciliacao_conciliacao_id'), table_name='arquivos_conciliacao', schema='concilia')
    op.drop_table('arquivos_conciliacao', schema='concilia')
    op.drop_index(op.f('ix_concilia_conciliacoes_periodo'), table_name='conciliacoes', schema='concilia')
    op.drop_index(op.f('ix_concilia_conciliacoes_id'), table_name='conciliacoes', schema='concilia')
    op.drop_index(op.f('ix_concilia_conciliacoes_empresa_id'), table_name='conciliacoes', schema='concilia')
    op.drop_index(op.f('ix_concilia_conciliacoes_conta_contabil_id'), table_name='conciliacoes', schema='concilia')
    op.drop_table('conciliacoes', schema='concilia')
    op.drop_index('ix_plano_contas_empresa_conta', table_name='plano_contas', schema='concilia')
    op.drop_index(op.f('ix_concilia_plano_contas_id'), table_name='plano_contas', schema='concilia')
    op.drop_index(op.f('ix_concilia_plano_contas_empresa_id'), table_name='plano_contas', schema='concilia')
    op.drop_index(op.f('ix_concilia_plano_contas_conta_superior'), table_name='plano_contas', schema='concilia')
    op.drop_index(op.f('ix_concilia_plano_contas_conta_contabil'), table_name='plano_contas', schema='concilia')
    op.drop_table('plano_contas', schema='concilia')
    op.drop_index(op.f('ix_concilia_empresa_id'), table_name='empresa', schema='concilia')
    op.drop_index(op.f('ix_concilia_empresa_cnpj'), table_name='empresa', schema='concilia')
    op.drop_table('empresa', schema='concilia')
    # ### end Alembic commands ###
